#index:
#    path: /
#    controller: App\Controller\DefaultController::index
hello_world: # Nom humain
    path: /hello-world # L'URL
    controller: App\Controller\ExampleController::helloWorld # Mon contrôleur :: sa méthode
